# Clustering practical


Load the 'dataset_1.csv'

In [1]:
import pandas as pd

In [2]:
dataset_1 = pd.read_csv('./dataset_1.csv')

Display the scatter plot of the data

In [3]:
dataset_1

     Unnamed: 0  normalized_age  normalized_salary
0             0        0.680267          -0.016342
1             1        3.809518           0.798483
2             2       -1.661372          -0.577667
3             3       -0.257307          -0.155552
4             4        0.698017           0.174561
5             5        2.472265           0.567305
6             6        0.206848          -0.027434
7             7        0.567246           0.089083
8             8       -0.348769          -0.231471
9             9       -1.451963          -0.372945
10           10        1.111152           0.516746
11           11       -1.261681          -0.383310
12           12       -2.472422          -0.808722
13           13       -0.318213          -0.079449
14           14        2.497910           0.434466
15           15        0.642876           0.135770
16           16       -3.367354          -0.703540
17           17        0.265793           0.097331
18           18        2.044046           0.357923
19           19       -0.513915          -0.082188
20           20       -2.414030          -0.463152
21           21        3.316318           0.950937
22           22       -0.744726          -0.124265
23           23        1.321734           0.436276
24           24       -0.361658           0.076294
25           25        0.657734           0.244308
26           26       -2.007075          -0.421172
27           27        0.728164           0.174151
28           28        0.514202           0.114337
29           29       -0.616660          -0.081664
..          ...             ...                ...
970         970       -5.388682           3.839815
971         971       -5.680693           2.749695
972         972       -5.971242           3.415426
973         973       -5.992870           4.538807
974         974       -6.693470           2.298132
975         975       -6.683827           2.587294
976         976       -7.525252           2.559245
977         977       -6.457299           3.054960
978         978       -5.707540           2.131849
979         979       -5.369962           4.261570
980         980       -6.145800           4.102060
981         981       -5.860707           4.392112
982         982       -5.217902           1.905267
983         983       -5.986961           3.738027
984         984       -5.978617           2.974182
985         985       -5.111165           2.503102
986         986       -5.987739           3.226538
987         987       -6.233654           2.985910
988         988       -5.457484           3.302986
989         989       -6.566102           2.227113
990         990       -6.552372           3.000874
991         991       -6.111958           2.417630
992         992       -6.418705           1.935973
993         993       -5.707502           2.971987
994         994       -6.881851           3.020034
995         995       -5.060165           2.482045
996         996       -5.079404           2.773580
997         997       -5.861520           3.068426
998         998       -5.018934           3.110904
999         999       -6.799331           2.082321

[1000 rows x 3 columns]

Look on the documentation on how to run Kmeans and run a kmeans model with k = 2 on the dataset

Display each point of the data with a color depending on the cluster

## A second dataset

Load the the dataset_2.csv and display the scatter plot

With a for loop, train a kmeans model with k = 1, 2, ..., 20 and each time display the scatter plot and the loss of the model

How does the loss of the model change when you increase k ?

## A third dataset

Load and display the third dataset. 
Run a kmeans on it with k = 2

Run the Spectral clustering of scikit learn on it and display the results

Run the dbscan algorithm on it and display the results